---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # Check for GitHub Actions updates
    directory: "/" # The root directory where the Ansible role is located
    schedule:
      interval: "monthly" # Check for updates monthly
    commit-message:
      prefix: "[ci] "
