#!/bin/bash
set -e
cd openwisp-config/tests/
luacheck . -d -a -r
lua test_store_unmanaged.lua -v
lua test_restore_unmanaged.lua -v
lua test_uci_autoname.lua -v
lua test_utils.lua -v
lua test_remove_default_wifi.lua -v
