#!/bin/sh /etc/rc.common

START=100
STOP=15
USE_PROCD=1
PROG="openwisp_controller_http"
PROG_NAME="OpenWISP Controller (HTTP)"

EXTRA_HELP="        running Check if process is running"

process_running() {
    running=$(ps w | grep -vw "grep" | grep $PROG | wc -l)

    if [ "$running" == "0" ]; then
        return 0
    else
        return 1
    fi
}

start_service() {
    process_running

    echo " * starting $PROG_NAME..."
    procd_open_instance
    procd_set_param command "/etc/openwisp/$PROG"
    procd_set_param respawn
    procd_close_instance
    echo " * started"
}

service_triggers()
{
    procd_add_reload_trigger "openwisp"
}

stop_service() {
    echo " * stopping $PROG_NAME..."

    killall -q $PROG

    if [ "$?" == "0" ]; then
        echo " * stopped"
    else
        echo " * failed: no process running"
    fi
}

reload_service() {
    stop
    start
}

service_running() {
    process_running

    if [ "$?" == "1" ]; then
        echo " * $PROG_NAME is running"
    else
        echo " * $PROG_NAME is not running"
    fi
}
