#!/bin/sh

WORKING_DIR="/tmp/openwisp"
CONFIGURATION_FILE="$WORKING_DIR/configuration.tar.gz"
CONFIGURATION_CHECKSUM="$WORKING_DIR/configuration_checksum"
INTERVAL=$(uci get openwisp.@controller_http[0].interval)
BASE_URL=$(uci get openwisp.@controller_http[0].url)
KEY=$(uci get openwisp.@controller_http[0].key)
CONFIGURATION_URL="$BASE_URL/get_config/$KEY"
CHECKSUM_URL="$CONFIGURATION_URL.md5"

if [ -z "$BASE_URL" ] || [ -z "$KEY" ]; then
    logger -s "Required configuration keys are empty, check /etc/config/openwisp" \
           -t "openwisp" \
           -p 3
    return 1
fi

mkdir -p $WORKING_DIR

configuration_changed() {
    local LOCAL_CHECKSUM=$(cat $CONFIGURATION_CHECKSUM)
    REMOTE_CHECKSUM=$(uclient-fetch $CHECKSUM_URL -q -O -)

    if [ -z "$REMOTE_CHECKSUM" ]; then
        logger -s "Could not retrieve checksum from controller" \
               -t "openwisp" \
               -p 3
        return 2
    fi

    if [ "$LOCAL_CHECKSUM" != "$REMOTE_CHECKSUM" ]; then
        # store checksum
        printf $REMOTE_CHECKSUM > $CONFIGURATION_CHECKSUM
        logger -s "Configuration in controller has changed" \
               -t "openwisp" \
               -p 6
        return 1
    fi

    return 0
}

update_configuration() {
    # download configuration
    uclient-fetch $CONFIGURATION_URL -O $CONFIGURATION_FILE

    if [ "$?" != "4" ]; then
        logger -s "Could not retrieve configuration from controller" \
               -t "openwisp" \
               -p 3
        return 3
    fi

    # restore configuration
    sysupgrade -r $CONFIGURATION_FILE

    if [ "$?" != "0" ]; then
        logger -s "Could not restore configuration successfully" \
               -t "openwisp" \
               -p 2
        return 4
    fi

    /sbin/reload_config

    logger -s "Configuration restored and applied" \
           -t "openwisp" \
           -p 6
}

while true
do
    configuration_changed

    if [ "$?" == "1" ]; then
        update_configuration
    fi

    sleep $INTERVAL
done
